-- GRANT SELECT, INSERT (columns) kept table-level SELECT, which still exposed pin_hash.
-- Column SELECT must be granted on its own.

REVOKE SELECT ON TABLE public.employees FROM anon, authenticated;

GRANT SELECT (
  id,
  user_id,
  company_id,
  name,
  surname,
  employee_code,
  employment_type,
  access_level,
  worker_type,
  position,
  branch,
  employment_date,
  hourly_rate,
  daily_rate,
  weekly_rate,
  monthly_salary,
  overtime_rate,
  double_time_rate,
  daily_hours,
  work_days_weekly,
  email,
  phone,
  manager_user_id,
  is_active,
  profile_photo_url,
  id_number,
  bank_account,
  bank_name,
  bank_branch_code,
  created_at,
  login_password_ready,
  employment_type_label,
  shift_template_id,
  registration_status,
  bank_details_updated_at,
  bank_details_updated_by,
  pay_basis,
  paye_rate_percent,
  uif_exempt,
  termination_date,
  medical_aid_deduction,
  pension_deduction,
  union_deduction,
  pay_full_monthly_salary,
  paye_fixed_amount,
  uif_rate_percent,
  uif_fixed_amount,
  tax_number,
  paye_reference,
  medical_aid_member_number,
  pension_fund_number,
  tax_directive_number,
  tax_directive_rate_percent,
  date_of_birth,
  cost_center,
  pin_set_at,
  pin_reset_required,
  pin_failed_attempts,
  pin_locked_until,
  login_failed_attempts,
  is_account_locked,
  locked_at,
  locked_reason,
  branch_id,
  manager_id,
  pay_by_hour,
  account_type,
  department
) ON TABLE public.employees TO anon, authenticated;
