-- Audit + role foundation
-- Run this once in Supabase SQL editor.

set search_path = public;

-- ---------------------------------------------------------------------------
-- 1) Role model expansion (beyond generic "hr")
-- ---------------------------------------------------------------------------

alter table public.hr_users
  add column if not exists display_name text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'hr_users_role_chk'
  ) then
    alter table public.hr_users
      add constraint hr_users_role_chk
      check (role in ('owner', 'admin', 'manager', 'payroll', 'viewer'));
  end if;
exception
  when duplicate_object then null;
end;
$$;

-- Migrate legacy role labels to valid role set.
update public.hr_users
set role = 'admin'
where role is null
   or role = ''
   or role = 'hr_admin'
   or role = 'hr';

-- ---------------------------------------------------------------------------
-- 2) created_by / updated_by columns (tracked by auth uid)
-- ---------------------------------------------------------------------------

-- Add actor columns on key business tables.
alter table public.employees add column if not exists created_by uuid;
alter table public.employees add column if not exists updated_by uuid;

alter table public.punches add column if not exists created_by uuid;
alter table public.punches add column if not exists updated_by uuid;

alter table public.clients add column if not exists created_by uuid;
alter table public.clients add column if not exists updated_by uuid;

alter table public.sites add column if not exists created_by uuid;
alter table public.sites add column if not exists updated_by uuid;

alter table public.jobs add column if not exists created_by uuid;
alter table public.jobs add column if not exists updated_by uuid;

alter table public.job_cards add column if not exists created_by uuid;
alter table public.job_cards add column if not exists updated_by uuid;

alter table public.incidents add column if not exists created_by uuid;
alter table public.incidents add column if not exists updated_by uuid;

alter table public.inventory_items add column if not exists created_by uuid;
alter table public.inventory_items add column if not exists updated_by uuid;

alter table public.job_inventory_usage add column if not exists created_by uuid;
alter table public.job_inventory_usage add column if not exists updated_by uuid;

alter table public.payment_approvals add column if not exists created_by uuid;
alter table public.payment_approvals add column if not exists updated_by uuid;

-- Ensure updated_at exists where not present.
alter table public.employees add column if not exists updated_at timestamptz not null default now();
alter table public.punches add column if not exists updated_at timestamptz not null default now();
alter table public.clients add column if not exists updated_at timestamptz not null default now();
alter table public.sites add column if not exists updated_at timestamptz not null default now();
alter table public.jobs add column if not exists updated_at timestamptz not null default now();
alter table public.job_cards add column if not exists updated_at timestamptz not null default now();
alter table public.incidents add column if not exists updated_at timestamptz not null default now();
alter table public.inventory_items add column if not exists updated_at timestamptz not null default now();
alter table public.job_inventory_usage add column if not exists updated_at timestamptz not null default now();

-- ---------------------------------------------------------------------------
-- 3) Audit table
-- ---------------------------------------------------------------------------

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  company_id bigint null references public.companies(id) on delete set null,
  table_name text not null,
  operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  record_pk text null,
  actor_user_id uuid null,
  actor_role text null,
  changed_fields jsonb null,
  old_data jsonb null,
  new_data jsonb null,
  request_id text null,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_logs_company_created_at on public.audit_logs(company_id, created_at desc);
create index if not exists idx_audit_logs_table_created_at on public.audit_logs(table_name, created_at desc);
create index if not exists idx_audit_logs_actor_created_at on public.audit_logs(actor_user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- 4) Trigger helpers: actor stamping + audit capture
-- ---------------------------------------------------------------------------

create or replace function public.audit_set_actor_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid;
begin
  v_uid := auth.uid();

  if tg_op = 'INSERT' then
    if to_jsonb(new) ? 'created_by' and new.created_by is null then
      new.created_by := v_uid;
    end if;
    if to_jsonb(new) ? 'updated_by' then
      new.updated_by := v_uid;
    end if;
    if to_jsonb(new) ? 'updated_at' then
      new.updated_at := now();
    end if;
  elsif tg_op = 'UPDATE' then
    if to_jsonb(new) ? 'updated_by' then
      new.updated_by := v_uid;
    end if;
    if to_jsonb(new) ? 'updated_at' then
      new.updated_at := now();
    end if;
  end if;

  return new;
end;
$$;

create or replace function public.audit_capture_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid;
  v_role text;
  v_company_id bigint;
  v_record_pk text;
  v_old jsonb;
  v_new jsonb;
  v_changed jsonb;
begin
  v_uid := auth.uid();
  v_old := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  v_new := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;

  if v_uid is not null then
    select h.role
    into v_role
    from public.hr_users h
    where h.auth_user_id = v_uid
      and h.is_active = true
    limit 1;
  end if;

  v_company_id := coalesce(
    case
      when v_new ? 'company_id' and (v_new ->> 'company_id') ~ '^[0-9]+$'
        then (v_new ->> 'company_id')::bigint
      else null
    end,
    case
      when v_old ? 'company_id' and (v_old ->> 'company_id') ~ '^[0-9]+$'
        then (v_old ->> 'company_id')::bigint
      else null
    end
  );
  v_record_pk := coalesce(v_new ->> 'id', v_old ->> 'id');

  if tg_op = 'UPDATE' then
    select coalesce(
      jsonb_object_agg(n.key, jsonb_build_object('old', o.value, 'new', n.value)),
      '{}'::jsonb
    )
    into v_changed
    from jsonb_each(v_new) n
    join jsonb_each(v_old) o on o.key = n.key
    where n.value is distinct from o.value
      and n.key not in ('updated_at');
  else
    v_changed := null;
  end if;

  insert into public.audit_logs (
    company_id,
    table_name,
    operation,
    record_pk,
    actor_user_id,
    actor_role,
    changed_fields,
    old_data,
    new_data,
    request_id
  ) values (
    v_company_id,
    tg_table_name,
    tg_op,
    v_record_pk,
    v_uid,
    v_role,
    v_changed,
    v_old,
    v_new,
    current_setting('request.jwt.claim.jti', true)
  );

  return coalesce(new, old);
end;
$$;

-- ---------------------------------------------------------------------------
-- 5) Attach triggers to core business tables
-- ---------------------------------------------------------------------------

create or replace function public.audit_attach_triggers(p_table text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  execute format('drop trigger if exists trg_%I_actor on public.%I', p_table, p_table);
  execute format('drop trigger if exists trg_%I_audit on public.%I', p_table, p_table);

  execute format(
    'create trigger trg_%I_actor before insert or update on public.%I
     for each row execute function public.audit_set_actor_fields()',
    p_table, p_table
  );

  execute format(
    'create trigger trg_%I_audit after insert or update or delete on public.%I
     for each row execute function public.audit_capture_changes()',
    p_table, p_table
  );
end;
$$;

select public.audit_attach_triggers('employees');
select public.audit_attach_triggers('punches');
select public.audit_attach_triggers('clients');
select public.audit_attach_triggers('sites');
select public.audit_attach_triggers('jobs');
select public.audit_attach_triggers('job_cards');
select public.audit_attach_triggers('incidents');
select public.audit_attach_triggers('inventory_items');
select public.audit_attach_triggers('job_inventory_usage');
select public.audit_attach_triggers('payment_approvals');

-- ---------------------------------------------------------------------------
-- 6) RLS for audit logs (HR sees only own company audit)
-- ---------------------------------------------------------------------------

alter table public.audit_logs enable row level security;
alter table public.audit_logs force row level security;

drop policy if exists p_audit_logs_select_own_company on public.audit_logs;
create policy p_audit_logs_select_own_company
on public.audit_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.hr_users h
    where h.auth_user_id = auth.uid()
      and h.is_active = true
      and h.company_id = audit_logs.company_id
  )
);

revoke all on public.audit_logs from anon;
grant select on public.audit_logs to authenticated;
