-- Branch catalog foundation
-- Central branch list per company.

set search_path = public;

create table if not exists public.company_branches (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_company_branches_company_name_unique
  on public.company_branches(company_id, lower(name));

create index if not exists idx_company_branches_company_active
  on public.company_branches(company_id, is_active, name);

create or replace function public.branch_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

do $$
begin
  execute 'drop trigger if exists trg_company_branches_updated_at on public.company_branches';
  execute 'create trigger trg_company_branches_updated_at before update on public.company_branches for each row execute function public.branch_touch_updated_at()';
end;
$$;

alter table public.company_branches enable row level security;

drop policy if exists p_company_branches_hr_company_all on public.company_branches;
create policy p_company_branches_hr_company_all on public.company_branches
for all to authenticated
using (
  exists (
    select 1 from public.hr_users h
    where h.auth_user_id = auth.uid()
      and h.is_active = true
      and h.company_id = company_branches.company_id
  )
)
with check (
  exists (
    select 1 from public.hr_users h
    where h.auth_user_id = auth.uid()
      and h.is_active = true
      and h.company_id = company_branches.company_id
  )
);

grant select, insert, update, delete on public.company_branches to authenticated;
