-- Employee type catalog foundation
-- Central employee-type list per company + optional label on employees.

set search_path = public;

alter table public.employees
  add column if not exists employment_type_label text null;

update public.employees
set employment_type_label = coalesce(nullif(btrim(employment_type_label), ''), employment_type)
where employment_type_label is null or btrim(employment_type_label) = '';

create table if not exists public.company_employee_types (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_company_employee_types_company_name_unique
  on public.company_employee_types(company_id, lower(name));

create index if not exists idx_company_employee_types_company_active
  on public.company_employee_types(company_id, is_active, name);

create or replace function public.employee_type_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

do $$
begin
  execute 'drop trigger if exists trg_company_employee_types_updated_at on public.company_employee_types';
  execute 'create trigger trg_company_employee_types_updated_at before update on public.company_employee_types for each row execute function public.employee_type_touch_updated_at()';
end;
$$;

insert into public.company_employee_types (company_id, name)
select c.id, t.name
from public.companies c
cross join (values ('Part-time'), ('Contract'), ('Permanent')) as t(name)
where not exists (
  select 1
  from public.company_employee_types et
  where et.company_id = c.id
    and lower(et.name) = lower(t.name)
);

alter table public.company_employee_types enable row level security;

drop policy if exists p_company_employee_types_hr_company_all on public.company_employee_types;
create policy p_company_employee_types_hr_company_all on public.company_employee_types
for all to authenticated
using (
  exists (
    select 1 from public.hr_users h
    where h.auth_user_id = auth.uid()
      and h.is_active = true
      and h.company_id = company_employee_types.company_id
  )
)
with check (
  exists (
    select 1 from public.hr_users h
    where h.auth_user_id = auth.uid()
      and h.is_active = true
      and h.company_id = company_employee_types.company_id
  )
);

grant select, insert, update, delete on public.company_employee_types to authenticated;
