-- Paperless expansion foundation
-- Covers:
-- 1) Digital forms + approvals + signature-ready submissions
-- 2) Document vault with versioning metadata
-- 3) Compliance tracking + assignment guardrails
-- 4) Client handover packs
-- 5) Export scheduling + integrations + automation rules

set search_path = public;

-- ---------------------------------------------------------------------------
-- Phase 1: forms + approvals
-- ---------------------------------------------------------------------------

create table if not exists public.form_templates (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  name text not null,
  form_type text not null,
  schema_json jsonb not null default '{}'::jsonb,
  requires_employee_signature boolean not null default false,
  requires_supervisor_signature boolean not null default false,
  requires_client_signature boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_form_templates_company on public.form_templates(company_id, is_active);

create table if not exists public.form_submissions (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  template_id bigint not null references public.form_templates(id) on delete restrict,
  employee_id bigint null references public.employees(id) on delete set null,
  job_id bigint null references public.jobs(id) on delete set null,
  status text not null default 'draft' check (status in ('draft', 'submitted', 'approved', 'rejected')),
  payload_json jsonb not null default '{}'::jsonb,
  employee_signature_url text null,
  supervisor_signature_url text null,
  client_signature_url text null,
  signed_pdf_url text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_form_submissions_company_status on public.form_submissions(company_id, status, created_at desc);

create table if not exists public.form_approvals (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  submission_id bigint not null references public.form_submissions(id) on delete cascade,
  step_order int not null default 1,
  required_role text not null default 'manager',
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  approver_user_id uuid null references auth.users(id) on delete set null,
  comments text null,
  acted_at timestamptz null,
  created_at timestamptz not null default now(),
  unique (submission_id, step_order)
);

create index if not exists idx_form_approvals_submission on public.form_approvals(submission_id, step_order);

-- ---------------------------------------------------------------------------
-- Phase 1: document vault
-- ---------------------------------------------------------------------------

create table if not exists public.document_files (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  employee_id bigint null references public.employees(id) on delete set null,
  job_id bigint null references public.jobs(id) on delete set null,
  client_id bigint null references public.clients(id) on delete set null,
  category text not null,
  title text not null,
  file_url text not null,
  mime_type text null,
  file_size_bytes bigint null,
  version_no int not null default 1,
  parent_document_id bigint null references public.document_files(id) on delete set null,
  tags text[] not null default '{}',
  expiry_date date null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_document_files_company_created on public.document_files(company_id, created_at desc);
create index if not exists idx_document_files_employee on public.document_files(company_id, employee_id);
create index if not exists idx_document_files_job on public.document_files(company_id, job_id);

-- ---------------------------------------------------------------------------
-- Phase 2: compliance + handover
-- ---------------------------------------------------------------------------

create table if not exists public.compliance_requirements (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  title text not null,
  applies_to_job_category text null,
  validity_days int null,
  is_mandatory boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.employee_compliance_records (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  requirement_id bigint not null references public.compliance_requirements(id) on delete cascade,
  document_file_id bigint null references public.document_files(id) on delete set null,
  issued_on date null,
  expires_on date null,
  status text not null default 'valid' check (status in ('valid', 'expiring', 'expired', 'missing')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (employee_id, requirement_id)
);

create index if not exists idx_employee_compliance_company_status on public.employee_compliance_records(company_id, status, expires_on);

create table if not exists public.handover_packs (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  job_id bigint not null references public.jobs(id) on delete cascade,
  generated_pdf_url text null,
  checklist_json jsonb not null default '{}'::jsonb,
  shared_with_email text null,
  shared_at timestamptz null,
  download_token text null,
  download_expires_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (job_id)
);

-- ---------------------------------------------------------------------------
-- Phase 3: exports + integrations + automations
-- ---------------------------------------------------------------------------

create table if not exists public.scheduled_exports (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  export_type text not null,
  format text not null check (format in ('csv', 'xlsx', 'pdf')),
  cron_expr text not null,
  destination_email text null,
  destination_webhook text null,
  is_active boolean not null default true,
  last_run_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.integration_endpoints (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  provider text not null,
  config_json jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.automation_rules (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  name text not null,
  trigger_type text not null,
  trigger_config jsonb not null default '{}'::jsonb,
  action_type text not null,
  action_config jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_events (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  source text not null,
  severity text not null default 'info',
  title text not null,
  body text not null,
  target_role text null,
  target_employee_id bigint null references public.employees(id) on delete set null,
  delivered boolean not null default false,
  delivered_at timestamptz null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Updated-at trigger helper reuse
-- ---------------------------------------------------------------------------

create or replace function public.paperless_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

do $$
begin
  execute 'drop trigger if exists trg_form_templates_updated_at on public.form_templates';
  execute 'create trigger trg_form_templates_updated_at before update on public.form_templates for each row execute function public.paperless_touch_updated_at()';
  execute 'drop trigger if exists trg_form_submissions_updated_at on public.form_submissions';
  execute 'create trigger trg_form_submissions_updated_at before update on public.form_submissions for each row execute function public.paperless_touch_updated_at()';
  execute 'drop trigger if exists trg_document_files_updated_at on public.document_files';
  execute 'create trigger trg_document_files_updated_at before update on public.document_files for each row execute function public.paperless_touch_updated_at()';
  execute 'drop trigger if exists trg_employee_compliance_records_updated_at on public.employee_compliance_records';
  execute 'create trigger trg_employee_compliance_records_updated_at before update on public.employee_compliance_records for each row execute function public.paperless_touch_updated_at()';
  execute 'drop trigger if exists trg_handover_packs_updated_at on public.handover_packs';
  execute 'create trigger trg_handover_packs_updated_at before update on public.handover_packs for each row execute function public.paperless_touch_updated_at()';
  execute 'drop trigger if exists trg_scheduled_exports_updated_at on public.scheduled_exports';
  execute 'create trigger trg_scheduled_exports_updated_at before update on public.scheduled_exports for each row execute function public.paperless_touch_updated_at()';
  execute 'drop trigger if exists trg_integration_endpoints_updated_at on public.integration_endpoints';
  execute 'create trigger trg_integration_endpoints_updated_at before update on public.integration_endpoints for each row execute function public.paperless_touch_updated_at()';
  execute 'drop trigger if exists trg_automation_rules_updated_at on public.automation_rules';
  execute 'create trigger trg_automation_rules_updated_at before update on public.automation_rules for each row execute function public.paperless_touch_updated_at()';
end;
$$;

-- ---------------------------------------------------------------------------
-- Optional compliance guardrail for employee assignment
-- ---------------------------------------------------------------------------

create or replace function public.has_employee_mandatory_compliance(
  p_company_id bigint,
  p_employee_id bigint
)
returns boolean
language sql
stable
as $$
  select not exists (
    select 1
    from public.compliance_requirements r
    where r.company_id = p_company_id
      and r.is_mandatory = true
      and not exists (
        select 1
        from public.employee_compliance_records c
        where c.company_id = p_company_id
          and c.employee_id = p_employee_id
          and c.requirement_id = r.id
          and c.status = 'valid'
          and (c.expires_on is null or c.expires_on >= current_date)
      )
  );
$$;
