-- Smart Scheduling + Recipient Routing
-- Run once in Supabase SQL editor.

set search_path = public;

-- ---------------------------------------------------------------------------
-- Scheduling tables
-- ---------------------------------------------------------------------------

create table if not exists public.shift_templates (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  name text not null,
  site_id bigint null references public.sites(id) on delete set null,
  start_time time not null,
  end_time time not null,
  required_headcount int not null default 1 check (required_headcount > 0),
  branch text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shifts (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  site_id bigint null references public.sites(id) on delete set null,
  title text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  required_headcount int not null default 1 check (required_headcount > 0),
  branch text null,
  geofence_radius_m int not null default 200 check (geofence_radius_m > 0),
  status text not null default 'open' check (status in ('open', 'filled', 'in_progress', 'completed', 'cancelled')),
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create index if not exists idx_shifts_company_starts on public.shifts(company_id, starts_at);
create index if not exists idx_shifts_company_status on public.shifts(company_id, status);

create table if not exists public.shift_assignments (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  shift_id bigint not null references public.shifts(id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  status text not null default 'offered' check (status in ('offered', 'accepted', 'declined', 'no_show', 'completed')),
  score numeric(10,2) null,
  score_reason text null,
  offered_at timestamptz not null default now(),
  responded_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (shift_id, employee_id)
);

create index if not exists idx_shift_assignments_company_employee on public.shift_assignments(company_id, employee_id, status);
create index if not exists idx_shift_assignments_shift_status on public.shift_assignments(shift_id, status);

create table if not exists public.shift_events (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  shift_id bigint not null references public.shifts(id) on delete cascade,
  assignment_id bigint null references public.shift_assignments(id) on delete set null,
  employee_id bigint null references public.employees(id) on delete set null,
  event_type text not null check (event_type in ('late_checkin', 'no_show', 'overtime_exception', 'geofence_block', 'window_block', 'manual_override')),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_shift_events_company_created on public.shift_events(company_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Recipient routing and notifications
-- ---------------------------------------------------------------------------

create table if not exists public.submission_recipients (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  submission_type text not null check (submission_type in ('incident', 'job_request')),
  submission_id bigint not null,
  recipient_user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (submission_type, submission_id, recipient_user_id)
);

create index if not exists idx_submission_recipients_company_recipient on public.submission_recipients(company_id, recipient_user_id, created_at desc);

create table if not exists public.notification_queue (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  recipient_user_id uuid not null references auth.users(id) on delete cascade,
  channel text not null default 'in_app' check (channel in ('in_app', 'email', 'webhook')),
  source text not null,
  title text not null,
  body text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed')),
  sent_at timestamptz null,
  created_at timestamptz not null default now()
);

create index if not exists idx_notification_queue_company_recipient on public.notification_queue(company_id, recipient_user_id, status, created_at desc);

-- ---------------------------------------------------------------------------
-- Employee job request submissions
-- ---------------------------------------------------------------------------

create table if not exists public.employee_job_requests (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  title text not null,
  description text null,
  preferred_date date null,
  status text not null default 'submitted' check (status in ('submitted', 'approved', 'rejected', 'converted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_employee_job_requests_company_status on public.employee_job_requests(company_id, status, created_at desc);

-- ---------------------------------------------------------------------------
-- Trigger helper for updated_at
-- ---------------------------------------------------------------------------

create or replace function public.smart_sched_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

do $$
begin
  execute 'drop trigger if exists trg_shift_templates_updated_at on public.shift_templates';
  execute 'create trigger trg_shift_templates_updated_at before update on public.shift_templates for each row execute function public.smart_sched_touch_updated_at()';
  execute 'drop trigger if exists trg_shifts_updated_at on public.shifts';
  execute 'create trigger trg_shifts_updated_at before update on public.shifts for each row execute function public.smart_sched_touch_updated_at()';
  execute 'drop trigger if exists trg_shift_assignments_updated_at on public.shift_assignments';
  execute 'create trigger trg_shift_assignments_updated_at before update on public.shift_assignments for each row execute function public.smart_sched_touch_updated_at()';
  execute 'drop trigger if exists trg_employee_job_requests_updated_at on public.employee_job_requests';
  execute 'create trigger trg_employee_job_requests_updated_at before update on public.employee_job_requests for each row execute function public.smart_sched_touch_updated_at()';
end;
$$;

-- ---------------------------------------------------------------------------
-- SQL helpers
-- ---------------------------------------------------------------------------

create or replace function public.employee_has_shift_overlap(
  p_company_id bigint,
  p_employee_id bigint,
  p_starts_at timestamptz,
  p_ends_at timestamptz
)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.shift_assignments a
    join public.shifts s on s.id = a.shift_id and s.company_id = a.company_id
    where a.company_id = p_company_id
      and a.employee_id = p_employee_id
      and a.status in ('offered', 'accepted', 'completed')
      and s.status in ('open', 'filled', 'in_progress', 'completed')
      and tstzrange(s.starts_at, s.ends_at, '[)') && tstzrange(p_starts_at, p_ends_at, '[)')
  );
$$;

create or replace function public.shift_assignment_score(
  p_company_id bigint,
  p_employee_id bigint,
  p_shift_id bigint
)
returns table(score numeric, reason text)
language plpgsql
stable
as $$
declare
  v_branch text;
  v_emp_branch text;
  v_score numeric := 100;
begin
  select s.branch into v_branch
  from public.shifts s
  where s.id = p_shift_id and s.company_id = p_company_id;

  select e.branch into v_emp_branch
  from public.employees e
  where e.id = p_employee_id and e.company_id = p_company_id;

  if public.employee_has_shift_overlap(p_company_id, p_employee_id, (select starts_at from public.shifts where id = p_shift_id), (select ends_at from public.shifts where id = p_shift_id)) then
    v_score := v_score - 70;
  end if;
  if v_branch is not null and v_emp_branch is not null and lower(v_branch) <> lower(v_emp_branch) then
    v_score := v_score - 10;
  end if;
  if not public.has_employee_mandatory_compliance(p_company_id, p_employee_id) then
    v_score := v_score - 40;
  end if;

  return query select greatest(v_score, 0), 'branch/compliance/availability baseline';
end;
$$;

-- ---------------------------------------------------------------------------
-- RLS + grants
-- ---------------------------------------------------------------------------

alter table public.shift_templates enable row level security;
alter table public.shifts enable row level security;
alter table public.shift_assignments enable row level security;
alter table public.shift_events enable row level security;
alter table public.submission_recipients enable row level security;
alter table public.notification_queue enable row level security;
alter table public.employee_job_requests enable row level security;

drop policy if exists p_shifts_hr_company_all on public.shifts;
create policy p_shifts_hr_company_all on public.shifts
for all to authenticated
using (
  exists (
    select 1 from public.hr_users h
    where h.auth_user_id = auth.uid()
      and h.is_active = true
      and h.company_id = shifts.company_id
  )
)
with check (
  exists (
    select 1 from public.hr_users h
    where h.auth_user_id = auth.uid()
      and h.is_active = true
      and h.company_id = shifts.company_id
  )
);

drop policy if exists p_shift_assignments_hr_company_all on public.shift_assignments;
create policy p_shift_assignments_hr_company_all on public.shift_assignments
for all to authenticated
using (
  exists (
    select 1 from public.hr_users h
    where h.auth_user_id = auth.uid()
      and h.is_active = true
      and h.company_id = shift_assignments.company_id
  )
)
with check (
  exists (
    select 1 from public.hr_users h
    where h.auth_user_id = auth.uid()
      and h.is_active = true
      and h.company_id = shift_assignments.company_id
  )
);

drop policy if exists p_submission_recipients_hr_company_all on public.submission_recipients;
create policy p_submission_recipients_hr_company_all on public.submission_recipients
for all to authenticated
using (
  exists (
    select 1 from public.hr_users h
    where h.auth_user_id = auth.uid()
      and h.is_active = true
      and h.company_id = submission_recipients.company_id
  )
)
with check (
  exists (
    select 1 from public.hr_users h
    where h.auth_user_id = auth.uid()
      and h.is_active = true
      and h.company_id = submission_recipients.company_id
  )
);

grant select, insert, update, delete on public.shifts to authenticated;
grant select, insert, update, delete on public.shift_assignments to authenticated;
grant select, insert, update, delete on public.shift_events to authenticated;
grant select, insert, update, delete on public.submission_recipients to authenticated;
grant select, insert, update, delete on public.notification_queue to authenticated;
grant select, insert, update, delete on public.employee_job_requests to authenticated;
grant select, insert, update, delete on public.shift_templates to authenticated;

